runtime: nodejs18

handlers:
  # Serve static files for React
  - url: /static
    static_dir: build/static
  - url: /(.*\.(js|css|html|json|ico|png|jpg))
    static_files: build/\1
    upload: build/.*\.(js|css|html|json|ico|png|jpg)

  # API requests
  - url: /Hii
    script: auto
    secure: always # Keep HTTPS on App Engine

  # Default route
  - url: /.*
    script: auto
